-- Oracle Architecture Arena initial Autonomous Database schema.
-- Requires Autonomous Database with native JSON and VECTOR support.
-- IDs are generated by the application as UUID-style strings.

create table oaa_use_cases (
  id varchar2(64) primary key,
  title varchar2(240) not null,
  account_name varchar2(240),
  competitor varchar2(40) not null,
  strategy_domain varchar2(40) not null,
  discovery_confidence varchar2(20) not null,
  raw_customer_signal clob not null,
  status varchar2(30) default 'active' not null,
  source_type varchar2(30) default 'user' not null,
  tags_json json,
  owner_id varchar2(128),
  created_at timestamp with time zone default systimestamp not null,
  updated_at timestamp with time zone default systimestamp not null,
  constraint oaa_use_cases_competitor_ck check (
    competitor in ('Databricks', 'Snowflake', 'AWS', 'Azure', 'Google Cloud', 'Other')
  ),
  constraint oaa_use_cases_domain_ck check (
    strategy_domain in (
      'database-modernization',
      'ai-ml-platform',
      'lakehouse-modernization',
      'sovereign-deployment'
    )
  ),
  constraint oaa_use_cases_confidence_ck check (
    discovery_confidence in ('Sparse', 'Directional', 'Validated')
  ),
  constraint oaa_use_cases_status_ck check (
    status in ('active', 'archived', 'deleted')
  ),
  constraint oaa_use_cases_source_type_ck check (
    source_type in ('user', 'seed', 'smoke_test', 'imported')
  )
);

create index oaa_use_cases_updated_ix on oaa_use_cases (updated_at desc);
create index oaa_use_cases_competitor_ix on oaa_use_cases (competitor);
create index oaa_use_cases_domain_ix on oaa_use_cases (strategy_domain);

create table oaa_assist_runs (
  id varchar2(64) primary key,
  use_case_id varchar2(64) not null,
  input_json json not null,
  brief_json json not null,
  generation_mode varchar2(20) not null,
  model varchar2(80),
  warning varchar2(1000),
  rag_context_json json,
  latency_ms number,
  created_at timestamp with time zone default systimestamp not null,
  constraint oaa_assist_runs_use_case_fk foreign key (use_case_id)
    references oaa_use_cases (id),
  constraint oaa_assist_runs_mode_ck check (
    generation_mode in ('llm', 'mock')
  )
);

create index oaa_assist_runs_case_ix on oaa_assist_runs (use_case_id, created_at desc);

create table oaa_debate_runs (
  id varchar2(64) primary key,
  use_case_id varchar2(64) not null,
  assist_run_id varchar2(64),
  input_json json not null,
  debate_json json not null,
  generation_mode varchar2(20) not null,
  model varchar2(80),
  reasoning_effort varchar2(30),
  rag_context_json json,
  latency_ms number,
  created_at timestamp with time zone default systimestamp not null,
  constraint oaa_debate_runs_case_fk foreign key (use_case_id)
    references oaa_use_cases (id),
  constraint oaa_debate_runs_assist_fk foreign key (assist_run_id)
    references oaa_assist_runs (id),
  constraint oaa_debate_runs_mode_ck check (
    generation_mode in ('llm', 'mock')
  )
);

create index oaa_debate_runs_case_ix on oaa_debate_runs (use_case_id, created_at desc);

create table oaa_architecture_blueprints (
  id varchar2(64) primary key,
  use_case_id varchar2(64) not null,
  debate_run_id varchar2(64),
  title varchar2(240) not null,
  summary clob,
  status varchar2(30) default 'generated' not null,
  confidence number(5, 2),
  blueprint_json json not null,
  created_at timestamp with time zone default systimestamp not null,
  updated_at timestamp with time zone default systimestamp not null,
  constraint oaa_blueprints_case_fk foreign key (use_case_id)
    references oaa_use_cases (id),
  constraint oaa_blueprints_debate_fk foreign key (debate_run_id)
    references oaa_debate_runs (id),
  constraint oaa_blueprints_status_ck check (
    status in ('generated', 'review', 'validated', 'retired')
  )
);

create index oaa_blueprints_case_ix on oaa_architecture_blueprints (use_case_id, updated_at desc);
create index oaa_blueprints_status_ix on oaa_architecture_blueprints (status);

create table oaa_whiteboard_sessions (
  id varchar2(64) primary key,
  use_case_id varchar2(64),
  title varchar2(240) not null,
  tldraw_snapshot_json json,
  notes_json json,
  status varchar2(30) default 'active' not null,
  created_at timestamp with time zone default systimestamp not null,
  updated_at timestamp with time zone default systimestamp not null,
  constraint oaa_whiteboards_case_fk foreign key (use_case_id)
    references oaa_use_cases (id),
  constraint oaa_whiteboards_status_ck check (
    status in ('active', 'archived', 'deleted')
  )
);

create index oaa_whiteboards_case_ix on oaa_whiteboard_sessions (use_case_id, updated_at desc);

create table oaa_smoke_test_runs (
  id varchar2(64) primary key,
  use_case_id varchar2(64),
  title varchar2(240) not null,
  status varchar2(30) not null,
  scenario_json json not null,
  steps_json json,
  findings_json json,
  artifact_prefix varchar2(1024),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone default systimestamp not null,
  constraint oaa_smoke_runs_case_fk foreign key (use_case_id)
    references oaa_use_cases (id),
  constraint oaa_smoke_runs_status_ck check (
    status in ('planned', 'running', 'passed', 'failed', 'blocked')
  )
);

create index oaa_smoke_runs_case_ix on oaa_smoke_test_runs (use_case_id, created_at desc);
create index oaa_smoke_runs_status_ix on oaa_smoke_test_runs (status);

create table oaa_artifacts (
  id varchar2(64) primary key,
  owning_entity_type varchar2(60),
  owning_entity_id varchar2(64),
  storage_provider varchar2(40) default 'LOCAL_FS' not null,
  storage_path varchar2(2048) not null,
  original_filename varchar2(512),
  display_name varchar2(512),
  mime_type varchar2(160),
  byte_size number,
  checksum_sha256 varchar2(128),
  metadata_json json,
  created_at timestamp with time zone default systimestamp not null,
  constraint oaa_artifacts_provider_ck check (
    storage_provider in ('LOCAL_FS', 'OCI_OBJECT_STORAGE')
  )
);

create index oaa_artifacts_owner_ix on oaa_artifacts (owning_entity_type, owning_entity_id);
create index oaa_artifacts_provider_ix on oaa_artifacts (storage_provider);

create table oaa_knowledge_documents (
  id varchar2(64) primary key,
  artifact_id varchar2(64),
  title varchar2(300) not null,
  source_type varchar2(40) not null,
  strategy_domain varchar2(40),
  competitor varchar2(40),
  content_hash varchar2(128),
  mime_type varchar2(160),
  classification varchar2(40) default 'internal' not null,
  status varchar2(30) default 'active' not null,
  metadata_json json,
  created_at timestamp with time zone default systimestamp not null,
  updated_at timestamp with time zone default systimestamp not null,
  constraint oaa_knowledge_docs_artifact_fk foreign key (artifact_id)
    references oaa_artifacts (id),
  constraint oaa_knowledge_docs_source_ck check (
    source_type in (
      'oracle-capability',
      'competitive-context',
      'architecture-pattern',
      'governance-pattern',
      'customer-document',
      'smoke-test'
    )
  ),
  constraint oaa_knowledge_docs_domain_ck check (
    strategy_domain is null or strategy_domain in (
      'database-modernization',
      'ai-ml-platform',
      'lakehouse-modernization',
      'sovereign-deployment',
      'cross-domain'
    )
  ),
  constraint oaa_knowledge_docs_competitor_ck check (
    competitor is null or competitor in (
      'Databricks',
      'Snowflake',
      'AWS',
      'Azure',
      'Google Cloud',
      'Other'
    )
  ),
  constraint oaa_knowledge_docs_class_ck check (
    classification in ('public', 'internal', 'confidential', 'restricted')
  ),
  constraint oaa_knowledge_docs_status_ck check (
    status in ('draft', 'processing', 'active', 'archived', 'failed')
  )
);

create index oaa_knowledge_docs_domain_ix on oaa_knowledge_documents (strategy_domain);
create index oaa_knowledge_docs_competitor_ix on oaa_knowledge_documents (competitor);
create index oaa_knowledge_docs_status_ix on oaa_knowledge_documents (status);

create table oaa_knowledge_chunks (
  id varchar2(64) primary key,
  document_id varchar2(64) not null,
  chunk_index number not null,
  heading varchar2(500),
  content clob not null,
  token_count number,
  embedding_model varchar2(80) not null,
  embedding vector(3072, float32),
  metadata_json json,
  created_at timestamp with time zone default systimestamp not null,
  constraint oaa_knowledge_chunks_doc_fk foreign key (document_id)
    references oaa_knowledge_documents (id),
  constraint oaa_knowledge_chunks_unique unique (document_id, chunk_index)
);

create index oaa_knowledge_chunks_doc_ix on oaa_knowledge_chunks (document_id, chunk_index);

create table oaa_retrieval_events (
  id varchar2(64) primary key,
  use_case_id varchar2(64),
  run_type varchar2(40) not null,
  run_id varchar2(64),
  query_text clob not null,
  embedding_model varchar2(80),
  filters_json json,
  results_json json,
  created_at timestamp with time zone default systimestamp not null,
  constraint oaa_retrieval_events_case_fk foreign key (use_case_id)
    references oaa_use_cases (id),
  constraint oaa_retrieval_events_type_ck check (
    run_type in ('competitive_assist', 'debate_arena', 'architecture_generator', 'manual_search')
  )
);

create index oaa_retrieval_events_case_ix on oaa_retrieval_events (use_case_id, created_at desc);
create index oaa_retrieval_events_run_ix on oaa_retrieval_events (run_type, run_id);
